# Generated by Django 4.2.1 on 2023-06-05 23:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id_filmes', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('diretor', models.CharField(max_length=255)),
                ('ano_lancamento', models.IntegerField()),
                ('idioma', models.CharField(max_length=50)),
                ('duracao', models.IntegerField()),
                ('producao', models.CharField(max_length=255)),
                ('criado_em', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id_livros', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('ano_lancamento', models.IntegerField()),
                ('paginas', models.IntegerField()),
                ('editora', models.CharField(max_length=255)),
                ('criado_em', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Musicas',
            fields=[
                ('id_musicas', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('artista', models.CharField(max_length=255)),
                ('ano_lancamento', models.IntegerField()),
                ('idioma', models.CharField(max_length=50)),
                ('duracao', models.IntegerField()),
                ('criado_em', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
